import Joi from "joi";

//Joi Validation for User
const validateUser = (userData) => {
  const schema = Joi.object({
    name01: Joi.string().required(),
    kana01: Joi.string().required(),
    zip01: Joi.string().min(3).max(5).required(),
    zip02: Joi.string().min(4).max(4).required(),
    pref: Joi.string().required(),
    addr01: Joi.string().required(),
    addr02: Joi.string().required(),
    email: Joi.string().email().required(),
    email_mobile: Joi.string().email(),
    tele01: Joi.string(),
    fax01: Joi.string(),
    img1: Joi.string(),
    img2: Joi.string(),
    img3: Joi.string(),
    password: Joi.string().required(),
    delegate_position: Joi.string(),
    delegate_name01: Joi.string(),
    delegate_name02: Joi.string(),
    delegate_kana01: Joi.string(),
    delegate_kana02: Joi.string(),
    charge_name01: Joi.string(),
    charge_name02: Joi.string(),
    charge_kana01: Joi.string(),
    charge_kana02: Joi.string(),
    corporate_url: Joi.string(),
    classified01: Joi.string(),
    classified02: Joi.string(),
    classified03: Joi.string(),
    classified04: Joi.string(),
    classified05: Joi.string(),
    capital: Joi.string(),
    business_content: Joi.string(),
    open_time: Joi.string(),
    close_time: Joi.string(),
    regular_holiday: Joi.string(),
    remarks: Joi.string(),
    establishment_date: Joi.date(),
    employees_number: Joi.number(),
    employees_site_area: Joi.string(),
    main_customer: Joi.string(),
    corporate_bank_name: Joi.string(),
    corporate_branch_name: Joi.string(),
    corporate_deposit_type: Joi.string(),
    corporate_account_number: Joi.string(),
    corporate_account_holder: Joi.string(),
    holiday_flg1: Joi.string(),
    holiday_flg2: Joi.string(),
    holiday_flg3: Joi.string(),
    holiday_flg4: Joi.string(),
    holiday_flg5: Joi.string(),
    holiday_flg6: Joi.string(),
    holiday_flg7: Joi.string(),
    usage_id: Joi.string(),
    corporate_name: Joi.string(),
    corporate_kana: Joi.string(),
    partner_flg: Joi.boolean(),
    termsAccepted: Joi.boolean().default(false),
    isVerified: Joi.boolean().default(false),
    passwordResetToken: Joi.string(),
    passwordResetExpires: Joi.date(),
  });

  return schema.validate(userData);
};

export { validateUser };
